### ISSUE TITLE
Je kan ook de buitenste loop variabele in de binnenste loop gebruiken

### ISSUE THREAD

**Issue by JeroenHeemskerk** [vincentlemstra/educom-csharp-sort#2]
https://github.com/vincentlemstra/educom-csharp-algorithm-1674047544/blob/14391217a332d8429414f6e3b4ac16ffe9e84c48/Organizer/ShiftHigestSort.cs#L32-L37

Je kan in plaats van n ook (high - low - i) gebruiken in de binnenste loop. dan loop je minder vaak door de lus waarbij je de laatste if overslaat.

Je kunt ook de buitenste loop laat aftellen 
```c#
 for (int i = high; i > low; i--)
 {
     for (int j = low; j <= i; j++) 
     { 
```

**Comment by vincentlemstra** [comment]
Even mee gespeeld. Leuk!
